server:
  port: ${PORT:8500}
#hostname: ${HOSTNAME:host.docker.internal:4200}

spring:
  application:
    name: versioning-service
  #  cloud:
  #    stream:
  #      function:
  #        definition: createdUserConsumer;createdGroupConsumer
  #      kafka:
  #        binder:
  #          brokers: ${KAFKA_URL}
  #          replicationFactor: 1
  #      bindings:
  #        createdUserConsumer-in-0:
  #          destination: "user-created"
  #          content-type: application/json
  #        createdProjectProducer-out-0:
  #          destination: "project-created"
  #          content-type: application/json
  #        deletedProjectProducer-out-0:
  #          destination: "project-deleted"
  #          content-type: application/json
  #        createdGroupConsumer-in-0:
  #          destination: "group-created"
  #          content-type: application/json
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
      file-size-threshold: 2MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/versionning-service1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true

target:
  file-service: localhost:9140

